@echo off
title Hyacinth
if not exist "Project/" mkdir Project
cd Project
if not exist "../Orchid/.internals_installed" echo const fs = require('fs'); if (!fs.existsSync('main.oc')) { fs.writeFileSync('main.oc', 'console.log(\'Hello, World!\');\n') } > HyacinthInternals.js
if not exist "../Orchid/.internals_installed" node HyacinthInternals.js
if not exist "../Orchid/.internals_installed" del HyacinthInternals.js /s /f
if not exist "../Orchid/.internals_installed" type nil > ../Orchid/.internals_installed
cd ..
if not exist "Orchid/" git clone https://github.com/kotinash/Orchid
if not exist "Orchid/" echo This directory is automatically generated by Hyacinth. Please do not edit it manually > Orchid/NOTE.txt
xcopy .\Project .\Orchid /sy
cd Orchid
rmdir "./.git" /s /q
if not exist ".installed" start cmd /k "title HyacinthDependencyInstaller & npm install terser"
if not exist ".installed" timeout /t 3 /nobreak
if not exist ".installed" taskkill /F /FI "WINDOWTITLE eq HyacinthDependencyInstaller*"
if not exist ".installed" start cmd /k "title HyacinthDependencyInstaller & npm install"
if not exist ".installed" timeout /t 15 /nobreak
if not exist ".installed" taskkill /F /FI "WINDOWTITLE eq HyacinthDependencyInstaller*"
if not exist ".installed" type nil > .installed
node index.js %1
node main.js
cd ..
pause
